menu:
  keppler_travel_reservation:
    name: reservations
    current: ['admin/travel/reservations']
    url_path: /admin/travel/reservations
    icon: layers
    model: KepplerTravel::Reservation

  keppler_travel_destination:
    name: destinations
    current: ['admin/travel/destinations']
    url_path: /admin/travel/destinations
    icon: location-pin
    model: KepplerTravel::Destination

  keppler_travel_tour:
    name: tours
    current: ['admin/travel/tours']
    url_path: /admin/travel/tours
    icon: map
    model: KepplerTravel::Tour

  keppler_travel_vehicle:
    name: vehicles
    current: ['admin/travel/vehicles']
    url_path: /admin/travel/vehicles
    icon: speedometer
    model: KepplerTravel::Vehicle
