modules:
 reservations:
    name: Reservation
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]
  
 destinations:
    name: Destination
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]
  
 transfers:
    name: Transfer
    actions: [
      'index', 'create', 'update',
      'destroy', 'download', 'upload',
      'clone'
    ]
  