# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email: example@gmail.com
  password:
  domain: gmail.com
  salt: \x92\xC1\xA5\x9B\x11\x7FYi\x84\xE3Js\x7F\xC1\xCC\x1E\xF7\x1D\xF8\xC2G\x91\xA1\xA2\xB1\xD3\a7\xDBR3\x9B
  key: n\x8D\e\x9Cn\x99\xAF\xDE\xB32A\xD5\xCER\xA3\xF6\x18O\xD1\xE6\x18\xC0\xB8\x1DC\xC6\xDAs\xA2\x95k\x8E
  passphrase: -\t\eB\x12\x9A\xCC\x95\x87\xC8\x15\xEC$\xC6\xB3\xF8JfO\xB2\x01\x96a/z/{\x14\xC0\xD9\xDE+
  secret_key_base: 84ef9e3a3032d77467dc6d95e988f2f128e6acc7513661e3e6b67a875d99bebabf19571d02d2ddb9face07dc45cb9aba821b4e93c2619deb2fee55a23818292c
  database:
    :host: localhost
    :name: receptivos
    :username: leonard  
    :password: 12345678
  ga_auth:
    :service_account_email_address: 911375046727-9n50de61u7flmue7s76qelsthlhqhnnl@developer.gserviceaccount.com
    :file_key_name: gauth_key.p12
    :account_id: 60688852

test:
  domain_name: example.com
  secret_key_base: b45cfc98355d328196d2e264760de949067607165e9c8d88f76aeba0dc486469e6c2ec641c49c92270961c4c6ff40645108f65e239ed4a10dcc46ab4905da72f
  database:
    :host: localhost
    :name: receptivos
    :username: root
    :password: 123456

production:
  email: example@gmail.com
  password: '#AsusPrime00'
  salt: \x92\xC1\xA5\x9B\x11\x7FYi\x84\xE3Js\x7F\xC1\xCC\x1E\xF7\x1D\xF8\xC2G\x91\xA1\xA2\xB1\xD3\a7\xDBR3\x9B
  key: n\x8D\e\x9Cn\x99\xAF\xDE\xB32A\xD5\xCER\xA3\xF6\x18O\xD1\xE6\x18\xC0\xB8\x1DC\xC6\xDAs\xA2\x95k\x8E
  passphrase: -\t\eB\x12\x9A\xCC\x95\x87\xC8\x15\xEC$\xC6\xB3\xF8JfO\xB2\x01\x96a/z/{\x14\xC0\xD9\xDE+
  domain: localhost
  domain_name: receptivo-colombia.herokuapp.com/
  host: https://receptivo-colombia.herokuapp.com/
  secret_key_base: 84ef9e3a3032d77467dc6d95e988f2f128e6acc7513661e3e6b67a875d99bebabf19571d02d2ddb9face07dc45cb9aba821b4e93c2619deb2fee55a23818292c
  database:
    :host: localhost
    :name: receptivos
    :username: root
    :password: 123456
  ga_auth:
    :service_account_email_address: 911375046727-9n50de61u7flmue7s76qelsthlhqhnnl@developer.gserviceaccount.com
    :file_key_name: gauth_key.p12
    :account_id: 60688852
